import { useState, useEffect, type FormEvent } from 'react';
import { LogOut, Pencil, Check } from 'lucide-react';
import { ref, update } from 'firebase/database';
import { db } from '../firebase';
import { useAuthContext } from '../context/AuthContext';
import { useAuth } from '../hooks/useAuth';
import {
  createCoupleAndInvite,
  redeemInviteCode,
  type RedeemInviteError,
} from '../services/coupling';
import { normalizeInviteCode } from '../lib/inviteCode';

type Choice = 'fresh' | 'join' | null;

const REDEEM_ERROR_TEXT: Record<RedeemInviteError, string> = {
  invalid_format: "That code doesn't look right. It should be 6 letters/numbers.",
  not_found: "We couldn't find that code. Double-check with your partner.",
  already_redeemed: 'That code has already been used.',
  expired: 'That code expired. Ask your partner for a fresh one.',
  self_redeem: "That's your own code — share it with your partner instead.",
};

// Heuristic: name was auto-generated by AuthContext bootstrap if it looks
// like an email-prefix (no spaces, all lowercase or alphanumeric).
function looksAutoGenerated(name: string, email: string): boolean {
  const prefix = email.split('@')[0]?.toLowerCase() ?? '';
  return name.trim().toLowerCase() === prefix;
}

export default function Pair() {
  const { user, userDoc } = useAuthContext();
  const { logout } = useAuth();

  const [choice, setChoice] = useState<Choice>(null);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');

  // Editable display name (stored locally until user moves forward).
  const [editingName, setEditingName] = useState(false);
  const [nameDraft, setNameDraft] = useState('');
  const [savingName, setSavingName] = useState(false);

  const [codeInput, setCodeInput] = useState('');

  useEffect(() => {
    if (!userDoc) return;
    setNameDraft(userDoc.displayName);
    // If the bootstrap auto-generated a name from the email, prompt to edit.
    if (looksAutoGenerated(userDoc.displayName, userDoc.email)) {
      setEditingName(true);
    }
  }, [userDoc]);

  if (!user || !userDoc) return null;

  const saveName = async () => {
    const cleaned = nameDraft.trim();
    if (cleaned.length === 0 || cleaned === userDoc.displayName) {
      setEditingName(false);
      return;
    }
    setSavingName(true);
    try {
      await update(ref(db, `users/${user.uid}`), { displayName: cleaned });
      setEditingName(false);
    } finally {
      setSavingName(false);
    }
  };

  const handleCreateFresh = async () => {
    setSubmitting(true);
    setError('');
    try {
      await createCoupleAndInvite(user.uid, userDoc.displayName);
      // App.tsx will route to Dashboard once coupleId is set on userDoc;
      // the invite code shows up there in the UnlinkedBanner.
    } catch {
      setError("We couldn't create your couple. Try again in a moment.");
      setSubmitting(false);
    }
  };

  const handleJoin = async (e: FormEvent) => {
    e.preventDefault();
    setSubmitting(true);
    setError('');
    const result = await redeemInviteCode(codeInput, user.uid, userDoc.displayName);
    if ('error' in result) {
      setError(REDEEM_ERROR_TEXT[result.error]);
      setSubmitting(false);
    }
    // On success, AuthContext picks up new coupleId and App.tsx routes to Dashboard.
  };

  return (
    <div className="min-h-screen flex flex-col px-8"
         style={{ background: 'linear-gradient(165deg, #0F0F1E 0%, #1A1A2E 40%, #16213E 100%)' }}>

      <header className="flex justify-between items-center pt-6">
        <h1 className="text-3xl font-semibold italic text-text-primary"
            style={{ fontFamily: "'Playfair Display', Georgia, serif" }}>
          Us
        </h1>
        <button
          onClick={logout}
          className="p-2 rounded-full hover:bg-white/5 transition-colors text-text-secondary/60 hover:text-text-primary"
          aria-label="Log out"
        >
          <LogOut size={18} />
        </button>
      </header>

      <div className="flex-1 flex flex-col justify-center max-w-sm mx-auto w-full">
        {choice === null && (
          <div className="space-y-5 animate-fade-in">
            {/* Editable name */}
            <div className="text-center mb-4">
              {editingName ? (
                <div className="flex items-center gap-2 justify-center">
                  <input
                    type="text"
                    autoFocus
                    value={nameDraft}
                    onChange={(e) => setNameDraft(e.target.value)}
                    onKeyDown={(e) => { if (e.key === 'Enter') saveName(); }}
                    placeholder="Your name"
                    className="px-4 py-2.5 rounded-xl bg-white/[0.04] border border-white/[0.08]
                               text-text-primary placeholder-text-secondary/40 text-base
                               focus:outline-none focus:border-accent/40 focus:ring-1 focus:ring-accent/20
                               text-center min-w-[180px]"
                  />
                  <button
                    onClick={saveName}
                    disabled={savingName || nameDraft.trim().length === 0}
                    className="p-2.5 rounded-full bg-accent/20 text-accent hover:bg-accent/30
                               disabled:opacity-40 transition-colors"
                    aria-label="Save name"
                  >
                    <Check size={16} />
                  </button>
                </div>
              ) : (
                <button
                  onClick={() => setEditingName(true)}
                  className="inline-flex items-center gap-2 text-text-primary text-lg
                             hover:text-accent transition-colors group"
                >
                  Welcome, {userDoc.displayName}
                  <Pencil size={14} className="opacity-30 group-hover:opacity-100 transition-opacity" />
                </button>
              )}
            </div>

            <p className="text-text-secondary/70 text-sm text-center mb-2">
              Are you the first one here?
            </p>

            <button
              onClick={() => setChoice('fresh')}
              className="w-full py-4 rounded-2xl font-medium text-sm text-bg-deep
                         bg-gradient-to-r from-accent to-[#d4b87a] hover:brightness-110
                         transition-all duration-200"
            >
              I'll send my partner a code
            </button>
            <button
              onClick={() => setChoice('join')}
              className="w-full py-4 rounded-2xl font-medium text-sm
                         bg-white/[0.04] border border-white/[0.08] text-text-primary
                         hover:bg-white/[0.08] transition-all duration-200"
            >
              My partner sent me a code
            </button>
          </div>
        )}

        {choice === 'fresh' && (
          <div className="space-y-5 animate-fade-in text-center">
            <p className="text-text-primary text-base leading-relaxed">
              We'll generate a 6-character code for you to share with your partner.
              They enter it on their device to link your accounts.
            </p>
            <button
              onClick={handleCreateFresh}
              disabled={submitting}
              className="w-full py-4 rounded-2xl font-medium text-sm text-bg-deep
                         bg-gradient-to-r from-accent to-[#d4b87a] hover:brightness-110
                         disabled:opacity-50 transition-all duration-200"
            >
              {submitting ? 'Setting up…' : 'Generate code'}
            </button>
            {error && <p className="text-feeling/80 text-sm">{error}</p>}
            <button
              type="button"
              onClick={() => { setChoice(null); setError(''); }}
              className="text-text-secondary/60 text-xs hover:text-text-primary transition-colors"
            >
              ← Back
            </button>
          </div>
        )}

        {choice === 'join' && (
          <form onSubmit={handleJoin} className="space-y-4 animate-fade-in">
            <p className="text-text-primary text-base text-center mb-2">
              Enter the 6-character code your partner sent you.
            </p>
            <input
              type="text"
              value={codeInput}
              onChange={(e) => setCodeInput(normalizeInviteCode(e.target.value))}
              placeholder="ABC234"
              maxLength={6}
              autoFocus
              autoCapitalize="characters"
              autoCorrect="off"
              spellCheck={false}
              className="w-full px-5 py-4 rounded-2xl bg-white/[0.04] border border-white/[0.08]
                         text-text-primary placeholder-text-secondary/40
                         text-2xl tracking-[0.3em] text-center font-mono
                         focus:outline-none focus:border-accent/40 focus:ring-1 focus:ring-accent/20
                         transition-all duration-200"
            />
            {error && <p className="text-feeling/80 text-sm text-center px-2">{error}</p>}
            <button
              type="submit"
              disabled={submitting || codeInput.length !== 6}
              className="w-full py-4 rounded-2xl font-medium text-sm text-bg-deep
                         bg-gradient-to-r from-accent to-[#d4b87a] hover:brightness-110
                         disabled:opacity-50 disabled:cursor-not-allowed
                         transition-all duration-200"
            >
              {submitting ? 'Linking…' : 'Link with my partner'}
            </button>
            <button
              type="button"
              onClick={() => { setChoice(null); setCodeInput(''); setError(''); }}
              className="w-full text-center text-text-secondary/60 text-xs hover:text-text-primary transition-colors"
            >
              ← Back
            </button>
          </form>
        )}
      </div>
    </div>
  );
}
